version: '3.7'

services:
  node_backend:
    build:
      context: .
    container_name: node_backend
    image: node-app
    ports:
      - 7001:7001
    environment:
      - PGUSER=postgres
      - PGPASSWORD=123456
      - PGDATABASE=defaultdb
      - PGHOST=db
    depends_on:
      - db
  db:
    container_name: db
    image: 'postgres:12'
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTRGRES_PASSWORD=123456
      - POSTGRES_DB=defaultdb
    volumes:
      - pgdata1:/var/lib/postgresql/data
volumes:
  pgdata1: {}

